"""empty message

Revision ID: 6b0377234e0f
Revises: 3e2b1a766ef2
Create Date: 2025-12-02 16:50:06.348145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b0377234e0f'
down_revision = '3e2b1a766ef2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charities', schema=None) as batch_op:
        batch_op.drop_column('logo_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_url', sa.VARCHAR(length=200), nullable=True))

    # ### end Alembic commands ###
